apiVersion: v1
kind: Pod
metadata:
  name: nlp
  namespace: default
  labels:
    name: nlp
spec:
  containers:
  - name: nlp
    image: jupyter/tensorflow-notebook:ubuntu-20.04
    ports:
      - containerPort: 8888
        hostPort: 10001
        protocol: TCP
    volumeMounts:
      - name: nfsdata
        mountPath: /home/jovyan/work
  volumes: 
    - name: nfsdata
      nfs:
          path: /home/kyokoz/data/NLP
          server: 192.168.100.100
